apiVersion: v2
name: gm-DiplomaProject-prod
description: A Helm chart for gm-DiplomaProject production environment
version: 0.1.0
dependencies:
  - name: app
    version: 0.1.0
    repository: "file://../../helm"