{{- range $appName, $appConfig := .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  namespace: {{ $.Values.global.namespace | default "default" }}
  labels:
    app: {{ $appName }}
spec:
  replicas: {{ $appConfig.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      serviceAccountName: {{ $.Values.global.serviceAccountName }}
      containers:
        - name: app
          image: "{{ $appConfig.image.repository }}:{{ $appConfig.image.tag }}"
          imagePullPolicy: {{ $appConfig.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ $appConfig.containerPort }}
          env:
            {{- with $appConfig.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if $.Values.global.corsOrigin }}
            - name: CORS_ORIGIN
              value: {{ $.Values.global.corsOrigin | quote }}
            {{- end }}
          resources:
            {{- toYaml ($appConfig.resources | default dict) | nindent 12 }}
{{- end }}