{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.name }}-ingress
  namespace: {{ .Values.global.namespace | default "default" }}
  annotations:
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          {{- range $appName, $appConfig := .Values.apps }}
          - path: {{ $appConfig.ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $appName }}
                port:
                  number: {{ $appConfig.service.port }}
          {{- end }}
{{- end }}