apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountName }}
  namespace: {{ .Values.global.namespace | default "default" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.global.serviceAccountName }}-{{ .Values.global.namespace }}-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.serviceAccountName }}-{{ .Values.global.namespace }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.serviceAccountName }}
    namespace: {{ .Values.global.namespace | default "default" }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.serviceAccountName }}-{{ .Values.global.namespace }}-role
  apiGroup: rbac.authorization.k8s.io