apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountName }}
  namespace: {{ .Values.global.namespace | default "default" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.serviceAccountName }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.serviceAccountName }}
    namespace: {{ .Values.global.namespace | default "default" }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io